name: Contexto de ejecucion en GitHub Actions 

on:
  workflow_dispatch:

jobs:
  mostrar-informacion:
    name: Informacion general del flujo
    runs-on: ubuntu-latest

    steps:
      - name: Mostrar informacion basica del repositorio
        run: |
          echo "Repositorio: ${{ github.repository }}"
          echo "Evento disparador: ${{ github.event_name }}"
          echo "Rama: ${{ github.ref }}"
          echo "Runner OS: ${{ runner.os }}"
          echo "Runner tipo: ${{ runner.name }}"
          echo "Arquitectura: ${{ runner.arch }}"

      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Mostrar archivos del repositorio
        run: |
          ls ${{ github.workspace }}
        run: echo "This job's status is ${{ job.status }}."

  variables-contexto:
    name: Mostrar contextos disponibles
    runs-on: ubuntu-latest

    steps:
      - name: Contexto GitHub
        run: echo "${{ toJSON(github) }}"

      - name: Contexto del Job
        run: echo "${{ toJSON(job) }}"

      - name: Contexto del Runner
        run: echo "${{ toJSON(runner) }}"

      - name: Contexto steps
        run: echo "steps: ${{ toJSON(steps) }}"

      - name: Contexto strategy
        run: echo "strategy: ${{ toJSON(strategy) }}"

      - name: Contexto matrix
        run:  echo "matrix: ${{ toJSON(matrix) }}"