name: Flujo solmunjim

on:
  workflow_dispatch:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  flujo-facil:
    runs-on: ubuntu-latest
    steps:
      - name: Evento recibido
        run: echo "Evento recibido ${{ github.event_name }}"

      - name: Acción externa - hora actual
        id: obtener_hora
        uses: josStorer/get-current-time@v2.0.0
        with:
          format: 'YYYY-MM-DD HH:mm:ss'

      - name: Mostrar hora
        run: echo "Hora actual ${{ steps.obtener_hora.outputs.time }}"
